---
version: 2
updates:
  # update GH actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"

  # update documentation dependencies
  - package-ecosystem: "npm"
    directory: "/docs/binaryrain-helper-toolkit-docs"
    schedule:
      interval: "monthly"

  # update python packages for aws helper
  - package-ecosystem: "uv"
    directories:
      - "packages/*"
    schedule:
      interval: "monthly"
