---
name: Publish Toolkit - DATAVERSE

"on":
  push:
    branches: [main]
    paths:
      - packages/binaryrain_helper_cloud_dataverse/**

env:
  WORKING_DIRECTORY: packages/binaryrain_helper_cloud_dataverse
  PACKAGE_NAME: binaryrain_helper_cloud_dataverse

jobs:
  uv-publish:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41

      - name: Install the project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv sync --all-extras --dev

      - name: Check Ruff
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv run ruff check .

      - name: Build the package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv build --package ${{ env.PACKAGE_NAME }} --no-sources

      - name: Publish the package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
