---
name: Test Toolkit - DATAFRAME

"on":
  pull_request:
    paths:
      - packages/binaryrain_helper_data_processing/**

env:
  WORKING_DIRECTORY: packages/binaryrain_helper_data_processing
  PACKAGE_NAME: binaryrain_helper_data_processing

jobs:
  uv-publish:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41

      - name: Format Ruff
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uvx ruff format .

      - name: Check Ruff
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uvx ruff check .

      - name: Install the project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv run pytest ./src/tests/ --cov ./src/binaryrain_helper_data_processing/ --cov-fail-under=85
